### ISSUE TITLE
Error While Run pas init

### ISSUE THREAD

**Issue by wahyutaufik** [xinix-technology/pas#24]
Error while run pas init:

``` bash
PAS_DEBUG=1 pas init krisanalfa/viper-arch viper-arch
```

get this errors:

```
E: unimplement yet for autoload:files
Error: unimplement yet for autoload:files
    at PHP.readManifest (/usr/lib/node_modules/pas/lib/profiles/php.js:98:27)
    at new Profile (/usr/lib/node_modules/pas/lib/profile.js:49:10)
    at Object.profile.detect (/usr/lib/node_modules/pas/lib/profile.js:126:16)
    at Package.initialize (/usr/lib/node_modules/pas/lib/pkg.js:32:32)
    at new Package (/usr/lib/node_modules/pas/lib/pkg.js:24:10)
    at Query.get (/usr/lib/node_modules/pas/lib/query.js:100:12)
    at query.then.then.then.task._ (/usr/lib/node_modules/pas/lib/tasks/init.js:40:31)
    at /usr/lib/node_modules/pas/node_modules/promise/lib/core.js:33:15
    at flush (/usr/lib/node_modules/pas/node_modules/promise/node_modules/asap/asap.js:27:13)
    at process._tickCallback (node.js:419:13)
.error

```

**Comment by reekoheek** [comment]
pas currently dont have implementation to autoload php from files

**Comment by reekoheek** [comment]
This functionality is done on newer version.
