### ISSUE TITLE
Error While Run pas version

### ISSUE THREAD

**Issue by wahyutaufik** [xinix-technology/pas#25]
Error while run pas version

```
PAS_DEBUG=1 pas version
E: Task "version" not found or error. [Error: Cannot find module '/home/wahyu/workspaces/pas-version/tasks/index']
Error: Task "version" not found or error. [Error: Cannot find module '/home/wahyu/workspaces/pas-version/tasks/index']
    at new Task (/usr/lib/node_modules/pas/lib/task.js:44:15)
    at getTask (/usr/lib/node_modules/pas/lib/task.js:143:12)
    at task (/usr/lib/node_modules/pas/lib/task.js:149:28)
    at null.<anonymous> (/usr/lib/node_modules/pas/lib/app.js:31:21)
    at /usr/lib/node_modules/pas/node_modules/promise/lib/core.js:33:15
    at flush (/usr/lib/node_modules/pas/node_modules/promise/node_modules/asap/asap.js:27:13)
    at process._tickCallback (node.js:419:13)
.error
```

**Comment by reekoheek** [comment]
there is no pas version task, may be you want to access pas help
