### ISSUE TITLE
Error while run pas init

### ISSUE THREAD

**Issue by wahyutaufik** [xinix-technology/pas#26]
I just run this

```
PAS_DEBUG=1 pas init reekoheek/docker-web-arch docker-file-server
```

got this error

```
0000.258 e| -> Error: Provider "packagist" is uninitialized yet
0000.258 e| Error: Provider "packagist" is uninitialized yet
0000.258 e|     at /home/xinix/.nvm/v0.11.16/lib/node_modules/pas/lib/provider.js:173:19
0000.258 e|     at Array.some (native)
0000.258 e|     at Function.provider.detect (/home/xinix/.nvm/v0.11.16/lib/node_modules/pas/lib/provider.js:171:26)
0000.258 e|     at new Query (/home/xinix/.nvm/v0.11.16/lib/node_modules/pas/lib/query.js:96:30)
0000.258 e|     at module.exports (/home/xinix/.nvm/v0.11.16/lib/node_modules/pas/lib/query.js:165:36)
0000.258 e|     at initTask.exec (/home/xinix/.nvm/v0.11.16/lib/node_modules/pas/lib/tasks/init.js:34:24)
0000.258 e|     at Task.run (/home/xinix/.nvm/v0.11.16/lib/node_modules/pas/lib/task.js:81:22)
0000.258 e|     at task (/home/xinix/.nvm/v0.11.16/lib/node_modules/pas/lib/task.js:162:42)
0000.258 e|     at null.<anonymous> (/home/xinix/.nvm/v0.11.16/lib/node_modules/pas/lib/app.js:46:21)
0000.258 e|     at runMicrotasksCallback (node.js:337:7)
0000.266 i| -> ERR

```

My node version is

```
| pas is package automation tools.
| version: 2.0.11
| node   : v0.11.16

```

**Comment by reekoheek** [comment]
Hey wahyu, at version 2.0.11, php functionality will be on different package,
you can install the plugin with name pas-php from npm

Thanks
