### ISSUE TITLE
Error on run "pas" after installing new version

### ISSUE THREAD

**Issue by wahyutaufik** [xinix-technology/pas#33]
After installing new version of pas, i just run

```
$ pas
```

then get this error:

```
undefined:1
~/.pas/config.json
^
SyntaxError: Unexpected token ~
    at Object.parse (native)
    at Object.module.exports (/home/wahyu/.nvm/versions/node/v0.12.6/lib/node_modules/pas/lib/config.js:41:27)
    at module.exports (/home/wahyu/.nvm/versions/node/v0.12.6/lib/node_modules/pas/lib/config.js:39:43)
    at Object.<anonymous> (/home/wahyu/.nvm/versions/node/v0.12.6/lib/node_modules/pas/lib/tasks/version.js:1:96)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
```

my node version:

```
$ node -v
v0.12.6
```

**Comment by reekoheek** [comment]
cannot recreate error, maybe already fixed on new version
please use new version 

```
npm install -g pas 
```
