### ISSUE TITLE
pas init because pas plugins.home not pointing to `/usr/local/lib/node_modules`

### ISSUE THREAD

**Issue by faridlab** [xinix-technology/pas#35]
$ PAS_DEBUG=1 pas init
000.006 Initialize new package:
000.015   name   : my/app
000.016   version: 0.0.1
000.016   profile: (autodetect)
000.020 ERROR    config is not defined
ReferenceError: config is not defined
    at Object.module.exports (/usr/local/lib/node_modules/pas/lib/tasks/init.js:48:42)
    at Object.Task.run (/usr/local/lib/node_modules/pas/lib/task.js:179:42)
    at null.<anonymous> (/usr/local/lib/node_modules/pas/lib/app.js:242:18)
    at App.run (/usr/local/lib/node_modules/pas/lib/app.js:240:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/pas/bin/pas:13:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)

**Comment by reekoheek** [comment]
FIXED, please use new version

```
npm install -g pas
```
