### ISSUE TITLE
pas module error show listing of modules

### ISSUE THREAD

**Issue by faridlab** [xinix-technology/pas#36]
$ PAS_DEBUG=1 pas module
000.872 Modules:
000.882 ERROR    Cannot read property 'match' of undefined
TypeError: Cannot read property 'match' of undefined
    at Object.module.exports.support (/usr/local/lib/node_modules/pas-cordova/profiles/cordova.js:40:26)
    at Object.<anonymous> (/usr/local/lib/node_modules/pas/lib/profile.js:180:33)
    at Array.some (native)
    at Object.Repository.detect (/usr/local/lib/node_modules/pas/lib/profile.js:175:40)
    at Object.<anonymous> (/usr/local/lib/node_modules/pas/lib/tasks/module.js:32:49)
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/lib/node_modules/pas/lib/tasks/module.js:31:30)

**Comment by reekoheek** [comment]
this should be pas-cordova issue. anyway I cannot recreate this bug with `pas-cordova` 3.0.4
